name: Build Dropbear for MIPSEL

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-dropbear:
    runs-on: ubuntu-latest
    name: Cross-compile Dropbear for mipsel-uclibc

    steps:
    - name: Checkout Dropbear source
      uses: actions/checkout@v4
      with:
        repository: "mkj/dropbear"
        

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget build-essential

    - name: Download and extract MIPS toolchain
      run: |
        mkdir -p toolchain
        wget https://github.com/JFC-Group/JF-Buildroot/releases/download/2015.08.1/mipsel-buildroot-linux-uclibc-toolchain-2015.08.1.tar
        tar -xf mipsel-buildroot-linux-uclibc-toolchain-2015.08.1.tar -C toolchain

    - name: Set environment variables
      run: |
        echo "TOOLCHAIN_DIR=$(pwd)/toolchain/usr" >> $GITHUB_ENV
        echo "$(pwd)/toolchain/usr/bin" >> $GITHUB_PATH
        echo "CROSS_COMPILE=mipsel-buildroot-linux-uclibc-" >> $GITHUB_ENV

    - name: Build Dropbear
      run: |
        make CC=${CROSS_COMPILE}gcc SCPPROGRESS=1 MULTI=1 PROGRAMS="dropbear dbclient dropbearkey dropbearconvert scp"

    - name: Archive built binaries
      uses: actions/upload-artifact@v4
      with:
        name: dropbear-mipsel
        path: |
          dropbearmulti
          dropbear
          dbclient
          dropbearkey
          dropbearconvert
          scp
