name: Build Dropbear for MIPSEL

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-dropbear:
    runs-on: ubuntu-latest
    name: Cross-compile Dropbear for mipsel-uclibc

    steps:
    - name: Checkout Dropbear source
      uses: actions/checkout@v4
      with:
        repository: "mkj/dropbear"
        

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget build-essential libc6-dev binutils libmpc-dev tree

    - name: Download and extract MIPS toolchain
      run: |
        wget https://github.com/JFC-Group/JF-Buildroot/releases/download/2015.08.1/mipsel-buildroot-linux-uclibc-toolchain-2015.08.1.tar
        tar -xf mipsel-buildroot-linux-uclibc-toolchain-2015.08.1.tar

    - name: Set environment variables
      run: |
        echo "TOOLCHAIN_DIR=$(pwd)/mipsel-buildroot-linux-uclibc-toolchain-2015.08.1/usr" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$(pwd)/mipsel-buildroot-linux-uclibc-toolchain-2015.08.1/usr/lib" >> $GITHUB_ENV
        echo "$(pwd)/mipsel-buildroot-linux-uclibc-toolchain-2015.08.1/usr/bin" >> $GITHUB_PATH
        echo "CROSS_COMPILE=mipsel-buildroot-linux-uclibc-" >> $GITHUB_ENV
        echo "CFLAGS=-Os -DLTC_NO_BSWAP -std=c99" >> $GITHUB_ENV

    - name: Build Dropbear
      run: |
        CC=${CROSS_COMPILE}gcc SCPPROGRESS=1 MULTI=1 PROGRAMS="dropbear dbclient dropbearkey dropbearconvert scp" ./configure --host=mipsel-buildroot-linux-uclibc --prefix=/usr --disable-zlib --disable-syslog || cat config.log
        make CC=${CROSS_COMPILE}gcc SCPPROGRESS=1 PROGRAMS="dropbear dbclient dropbearkey dropbearconvert scp"
        make strip

    - name: Read first line of CHANGES file
      id: changelog
      run: |
        echo "release_name=$(head -n 1 CHANGES)" >> "$GITHUB_OUTPUT"

    - name: Generate tag name (e.g. from version file or timestamp)
      id: tag
      run: |
        # Example: Use current date as tag
        TAG_NAME="release-$(date +%Y%m%d-%H%M%S)"
        echo "tag_name=$TAG_NAME" >> "$GITHUB_OUTPUT"

    - name: Create Release and Upload Binaries
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dropbear
          dbclient
          dropbearkey
          dropbearconvert
          scp
        name: Dropbear ${{ steps.changelog.outputs.release_name }}
        generate_release_notes: true
        tag_name: ${{ steps.tag.outputs.tag_name }}
        make_latest: true
        draft: false
        prerelease: ${{ github.ref_name != 'main' }}
        repository: rabilrbl/dropbear-mipsel
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
